# -*- coding: utf-8 -*-
"""Assignment1 (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ks5rFUCupRw7CC2_iKpH8zLrvRLuL1hM
"""

#Import the csv library
import csv

#Open the CSV file
with open('C:\\Users\\MVSR\\Desktop\\Dataset.csv','r')as csv_file:
    ###Use the csv.reader object to read the CSV file.
    csv_reader=csv.reader(csv_file)
    ### Extract the field names
    header = next(csv_reader)
# Extract the field names

#Load the data from a CSV file into memory using the CSV module.
#Open the CSV file
with open('C:\\Users\\MVSR\\Desktop\\Dataset.csv','r',encoding='utf8')as csv_file:
    #Use the csv.reader object to read the CSV file.
    csv_reader=csv.reader(csv_file)
    
   #Retrieve a name of listing, host_name, description, host_location, and the date the host was created for an individual host by host_id
  
    #To retrieve the data by host Id
    id = input("Enter host ID")
#gives us al list of everything in col 0
    for row in csv_reader:
        if row[0] == id:
            print("Name of listing:","        ",row[1])
            print("Host Name:","              ",row[3])
            print("Discription:","             ",row[2])
            print("Host Location:","           ",row[5])
            print("Date the host was created:","  ",row[4])
            break

#Load the data from a CSV file into memory using the CSV module.
#Open the CSV file
with open('C:\\Users\\MVSR\\Desktop\\Dataset.csv','r',encoding='utf8')as csv_file:
    #Use the csv.reader object to read the CSV file.
    csv_reader=csv.reader(csv_file)
    ###Retrieve host_name, property_type, price, minimum_nights, and maximum_nights of all Airbnb listing for a specified location
    ###To retrieve the data by specified location
    
    location  = input("Enter the location")
    ###Gives us a list of location in col 5
    count=0
    for row in csv_reader:
        if row[5] == location:
            count+=1;
            print("Details  ",count,"  for same location for ")
            print("Host Name:","        ",row[3])
            print("Property type","     ",row[13])
            print("Price:","             ",row[20])
            print("Minimum nights:","    ",row[21])
            print("Maximum nights:","    ",row[22])

###Retrieve room_type, accommodates, bathrooms, bedroom, and beds of all Airbnb listing for a specified property type
with open('C:\\Users\\MVSR\\Desktop\\Dataset.csv','r',encoding='utf8')as csv_file:
    ###Use the csv.reader object to read the CSV file.
    csv_reader=csv.reader(csv_file)
    value=0
    property = input("Enter property type:  ")   
    count=0
    for row in csv_reader:
        if row[13] == property:
            count=count+1;
            print("Details  ",count,"  for same property type  ")
            print("Room type:","    ",row[14])
            print("Accommodates:"," ",row[15])
            print("Bathrooms:","    ",row[16])
            print("Bedroom:","      ",row[17])
            print("Beds:","          ",row[18])

###Retrieve room_type, accommodates, bathrooms, bedroom, and beds of all Airbnb listing for a specified property type
with open('C:\\Users\\MVSR\\Desktop\\Dataset.csv','r',encoding='utf8')as csv_file:
    ###Use the csv.reader object to read the CSV file.
    csv_reader=csv.reader(csv_file)
    #Retrieve specific columns of your choice related to an individual host by location
    host = input("Enter host name :  ")
    count=0
    for row in csv_reader:
        if row[3] == host:
            count=count+1;
            print("Details  ",count,"  for same host name :  ")
            print("Name:","    ",row[1])
            print("Host Response:"," ",row[6])
            print("Room Type:","    ",row[15])